"""Minify web/index.html into index_html.h, the copy of the page stored in the ESP8266's flash.

    python minify.py           # rebuild index_html.h after editing web/index.html
    python minify.py --check   # only check that index_html.h is up to date (exit code 1 if not)

It removes comments and the spaces and line breaks that are only there for readability:
- HTML: comments are dropped. Whitespace containing a line break next to a tag is dropped,
  any other whitespace becomes one space.
- JavaScript (inside <script>): // and /* */ comments are dropped, and whitespace is removed
  except one space where two words would otherwise merge (like `const x`). Strings and regular
  expressions are kept as they are. Line breaks are removed too, so end statements with `;`.

Only needs Python 3.10+.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SOURCE = ROOT / "web" / "index.html"
HEADER = ROOT / "index_html.h"

SCRIPT = re.compile(r"(<script\b[^>]*>)(.*?)(</script>)", re.S | re.I)
WORD = re.compile(r"[\w$]")
# A "/" after one of these (or at the start) begins a regular expression, otherwise it's a division
REGEX_AFTER_CHAR = set("(,=:[!&|?{};+-*%<>~^")
REGEX_AFTER_WORD = ("return", "typeof", "case", "do", "else", "in", "of", "new", "delete", "void", "throw")


def minify_html(text):
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)

    def space(m):
        s = m.string
        if m.start() == 0 or m.end() == len(s):
            return ""  # next to a <script> tag or at the start/end of the page
        if "\n" in m.group() and (s[m.start() - 1] == ">" or s[m.end()] == "<"):
            return ""
        return " "

    return re.sub(r"\s+", space, text)


def needs_space(before, after):
    """Whether removing the whitespace between two characters would change the code."""
    if WORD.match(before) and WORD.match(after):
        return True  # const x, return a, async e
    return before == after and before in "+-"  # a - -b, a + +b


def regex_allowed(out):
    code = "".join(out).rstrip()
    if not code or code[-1] in REGEX_AFTER_CHAR:
        return True
    word = re.search(r"[\w$]+$", code)
    return bool(word) and word.group() in REGEX_AFTER_WORD


def skip_string(code, i):
    """Index just after the string or template literal starting at code[i]."""
    quote, j = code[i], i + 1
    while j < len(code) and code[j] != quote:
        j += 2 if code[j] == "\\" else 1
    if j >= len(code):
        raise ValueError(f"Unterminated string in the page's script: {code[i:i + 40]!r}")
    return j + 1


def skip_regex(code, i):
    """Index just after the regular expression (and its flags) starting at code[i]."""
    j, in_class = i + 1, False
    while j < len(code):
        c = code[j]
        if c == "\\":
            j += 2
            continue
        if c == "\n":
            break
        if c == "[":
            in_class = True
        elif c == "]":
            in_class = False
        elif c == "/" and not in_class:
            j += 1
            while j < len(code) and WORD.match(code[j]):
                j += 1
            return j
        j += 1
    raise ValueError(f"Unterminated regular expression in the page's script: {code[i:i + 40]!r}")


def minify_js(code):
    out, i, gap = [], 0, False  # gap: whitespace or a comment was skipped before the next token
    while i < len(code):
        c = code[i]
        if code.startswith("//", i):
            end = code.find("\n", i)
            i, gap = (len(code) if end < 0 else end), True
            continue
        if code.startswith("/*", i):
            end = code.find("*/", i + 2)
            if end < 0:
                raise ValueError("Unterminated /* comment in the page's script")
            i, gap = end + 2, True
            continue
        if c.isspace():
            i, gap = i + 1, True
            continue

        if c in "'\"`":
            end = skip_string(code, i)
        elif c == "/" and regex_allowed(out):
            end = skip_regex(code, i)
        else:
            end = i + 1
        token = code[i:end]
        if gap and out and needs_space(out[-1][-1], token[0]):
            out.append(" ")
        out.append(token)
        i, gap = end, False
    return "".join(out)


def minify(html):
    parts, pos = [], 0
    for m in SCRIPT.finditer(html):
        parts.append(minify_html(html[pos:m.end(1)]))  # HTML up to and including <script>
        parts.append(minify_js(m.group(2)))
        pos = m.start(3)
    parts.append(minify_html(html[pos:]))
    return "".join(parts)


def header(page):
    if ')rawliteral"' in page:
        raise ValueError('The page contains )rawliteral" which would end the C++ string early')
    return (
        "// Generated by minify.py from web/index.html: edit that file, then run `python minify.py`.\n"
        "// Stored in flash (PROGMEM) and sent as-is, so the page uses no RAM.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "\n"
        f'const char INDEX_HTML[] PROGMEM = R"rawliteral({page})rawliteral";\n'
    )


def build():
    """The minified page and the content of index_html.h for the current web/index.html."""
    page = minify(SOURCE.read_text(encoding="utf-8"))
    return page, header(page)


def header_up_to_date():
    return HEADER.exists() and HEADER.read_text(encoding="utf-8") == build()[1]


if __name__ == "__main__":
    try:
        page, content = build()
    except ValueError as e:
        sys.exit(f"Error: {e}")

    if "--check" in sys.argv[1:]:
        if header_up_to_date():
            print(f"{HEADER.name} is up to date")
            sys.exit(0)
        sys.exit(f"{HEADER.name} is out of date: run `python minify.py`")

    HEADER.write_text(content, encoding="utf-8", newline="\n")
    source_size = len(SOURCE.read_bytes())
    page_size = len(page.encode())
    print(f"{SOURCE.relative_to(ROOT).as_posix()}: {source_size:,} bytes -> "
          f"{HEADER.name}: {page_size:,} bytes ({100 - page_size * 100 // source_size}% smaller)")
